mespronos.reminder:
  type: config_object
  label: 'Mespronos Reminder Config'
  mapping:
    enabled:
      type: boolean
      label: 'Does the reminder are activated'
    hours:
      type: integer
      label: 'Hour before the day to send reminder'
